version: '3.8'

services:
  mariadb:
    container_name: mariadb104
    image: mariadb:10.4
    volumes:
      - ../../../volumes/mariadb/10.4:/var/lib/mysql
    ports:
      - "43104:3306"
    restart: unless-stopped
    command:
      --max_allowed_packet=128M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
      --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=magento
    networks:
      - my-dockers-network

networks:
  my-dockers-network:
    driver: bridge
